from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"   # Directory for input data files, such as zone types, zone data, and zones configuration in JSON format.
STARTING_CASE_DIR = ROOT / "Starting_Case" # Directory containing the starting building model file (ESBO_1zone.idm) that will be used as the basis for creating the zones and running simulations in IDA.
OUTPUT_DIR = ROOT / "output" # Directory for all output files generated by the workflow, including scripts, modified models, and simulation results. This directory will contain subdirectories for scripts, models, and results to keep the outputs organized.
SCRIPTS_DIR = OUTPUT_DIR / "scripts" # Subdirectory within OUTPUT_DIR for storing the generated LISP scripts that create the zones in the building model. Each script will be named based on the first zone's name for easy identification.
MODELS_DIR = OUTPUT_DIR / "models" # Subdirectory within OUTPUT_DIR for storing the modified building models after zones have been created and simulations have been run. Each model will be saved with a name based on the first zone's name and the simulation step (e.g., postSim.idm).
RESULTS_DIR = OUTPUT_DIR / "results" # Subdirectory within OUTPUT_DIR for storing the results of the simulations, including JSON and Excel files containing the zone results for each simulation type (heating, cooling, energy). Each results file will be named based on the first zone's name and the simulation type for easy identification.

# files
ZONE_TYPES_PATH = DATA_DIR / "zone_types.csv"  
ZONE_DATA_PATH = DATA_DIR / "zone_data.csv"
ZONES_JSON_PATH = DATA_DIR / "zones_5_orientations.json"
STARTING_MODEL_PATH = STARTING_CASE_DIR / "ESBO_1zone.idm"

# Update this before testing if IDA ICE is installed elsewhere.
IDA_ICE_BIN = Path(r"C:\Program Files (x86)\IDA_5_1_1_1\bin")


def ensure_output_dirs() -> None:
    for directory in (SCRIPTS_DIR, MODELS_DIR, RESULTS_DIR):
        directory.mkdir(parents=True, exist_ok=True)

